CREATE TABLE "config_detail_hierarchy" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "config_detail_id" BIGINT,
    "parent_config_detail_id" BIGINT,
    "son_config_detail_id" BIGINT,
    "attribute" json,

    CONSTRAINT fk_config_detail_id FOREIGN KEY (config_detail_id) REFERENCES config_details(id),
    CONSTRAINT fk_parent_config_detail_id FOREIGN KEY (parent_config_detail_id) REFERENCES config_details(id),
    CONSTRAINT fk_son_config_detail_id FOREIGN KEY (son_config_detail_id) REFERENCES config_details(id)
);

